### ISSUE TITLE
Cannot load files or files in directories with space characters

### ISSUE THREAD

**Issue by briantist** [tomaciazek/vscode-ansible#13]
### Summary

If a file has a space in its name, or a file is n a directory with a space in its name, the extension cannot load it and shows an error. 

This comes either in the form of a failed `ansible-playbook --syntax-check` (when the file name has a space):

> [internal-error] Unexpected error code 1 from execution of: ansible-playbook --syntax-check tests/integration/targets/connection_options/meta/main%20Z.yml

or load-failure if the directory contains a space:

> [load-failure] [Errno 2] No such file or directory: 'tests/integration/targets/auth_none%20copy/defaults/main.yml'
Description: Linter failed to process a YAML file, possible not an Ansible file.

The files show as green in explorer pane until you click on them, and then they turn red. They turn back to green when you click away.

It seems to be an issue of URL encoded paths, and having `%20` remain in the paths when trying to access files.

### Extension version

1.0.3

### VS Code version

1.58.2

### Ansible Version

```shell
2.11
```

### OS / Environment

Ubuntu 18.04 (WSL2)

### Relevant log output

```shell
[Info  - 8:18:26 PM] [ansible-lint] WARNING  Overriding detected file kind 'yaml' with 'playbook' for given positional argument: /home/briantist/code/ansible/ansible_collections/community/hashi_vault/tests/integration/targets/connection_options/meta/main%20Z.yml
```

**Comment by tomaciazek** [comment]
Thanks for reporting it. I've noticed this issue when someone else reported another issue on reddit regarding some `ENOENT` error. Both should be fixed with the new release.

**Comment by briantist** [comment]
Very nice, thanks Tomasz!
