### ISSUE TITLE
Windows CRLF EOL breaks syntax highlighting

### ISSUE THREAD

**Issue by asviel** [tomaciazek/vscode-ansible#14]
### Summary

TLDR: When end of line sequence is CRLF (\r\n), the syntax highlighting breaks down.

CRLF:
![image](https://user-images.githubusercontent.com/36459357/128258537-dee0a586-ad07-4b90-946a-94129a368260.png)

LF:
![image](https://user-images.githubusercontent.com/36459357/128258562-b2707cf7-e792-481e-800d-364f00f6dab9.png)

### Extension version

1.0.3

### VS Code version

1.58.2

### Ansible Version

```shell
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/asviel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
```

### OS / Environment

Windows 10, WSL (Ubuntu 20.04), ansible-lint 4.2.0

### Relevant log output

```shell
[Warn  - 12:38:06 AM] Standard output from ansible-lint is suspiciously empty.
[Info  - 12:38:06 AM] [ansible-lint] Usage: ansible-lint [options] [playbook.yml [playbook2 ...]]

ansible-lint: error: no such option: --offline
```

**Comment by tomaciazek** [comment]
Thanks for reporting! I've just released a version in which all CRLF line-ending issues should be fixed.

BTW, it seems like there's something wrong with your `ansible-lint` installation. You might be using some older version, which doesn't support the `--offline` option. Until you upgrade, you won't see any feedback from the linter in VS Code.
