### ISSUE TITLE
"spawn /bin/sh ENOENT" Errors

### ISSUE THREAD

**Issue by roadfox** [tomaciazek/vscode-ansible#24]
### Summary

Still getting "spawn /bin/sh ENOENT" and "spawnSync /bin/sh ENOENT" Errors when opening an Ansible YAML File

Situation:
VS Code installed on Windows Client (
Ansible Project opened via "Remote - SSH" extension
Path to ansible, ansible-lint and python are set

### Extension version

1.0.6

### VS Code version

1.59.1

### Ansible Version

```shell
ansible 2.10.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/test@dev.ctdatacenter.com/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
```

### OS / Environment

VS Code Versions:
Version: 1.59.1 (user setup)
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:56:46.957Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042

Remote - SSH
v0.65.7

**Comment by tomaciazek** [comment]
Thanks for reporting! The name of your home directory gave me the clue to that helped me pinpoint what was still wrong with handling of special characters. Sorry it took so long.

**Comment by AndreasUfert** [comment]
Hi,

my home directory contains an "@" and some ".". It's generated from a AD connected sssd so the home directory matches the pattern /home/username@my.realm.

With 1.0.7 I still get "spawn /bin/sh ENOENT".

Regards, Andreas

**Comment by tomaciazek** [comment]
Hi @AndreasUfert,
Sorry, I can't reproduce this issue any more, even with "."'s and "@"'s. Not even using Remote/SSH connection. Not even having a user directory with a domain name (with a ".") after an "@".
