### ISSUE TITLE
Json Error

### ISSUE THREAD

**Issue by jzielke84** [tomaciazek/vscode-ansible#9]
### Summary

Json error when using lint function: "Unexpected token a in JSON at position 0"

### Extension version

1.0.2

### VS Code version

1.58.2

### Ansible Version

```shell
ansible 2.10.12
  config file = /Users/user1/repos/repo1/ansible.cfg
  configured module search path = ['/Users/user1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.6 (default, Jun 29 2021, 05:25:02) [Clang 12.0.5 (clang-1205.0.22.9)]
```

### OS / Environment

ansible-lint 5.1.2 using ansible 2.10.12
MacOS 11.4

**Comment by tomaciazek** [comment]
There's not a lot to go about to reproduce this issue. Could you share a minimal file for which this issue happens? Also, there might be some output in `Output > Ansible Server` that might give additional clues as to what is the root cause.

**Comment by jzielke84** [comment]
It happens on every yml file i open. Example:
```yaml
ansible_python_interpreter: /usr/bin/python
ansible_user: ansible
ansible_become: false
```

Once I turn of the linting option of your extension it's gone. The output of vsc doesn't show anything in the output section regarding this issue.

**Comment by tomaciazek** [comment]
Looks like there's an issue with `ansible-lint` installation or configuration on your machine. I've prepared an update that will make it easier to pinpoint that.

**Comment by jzielke84** [comment]
@tomaciazek Strange, after the update, the error wirh activated lint funtction was gone.
